version: '3.4'
services:
  fcardre:
    image: evgeniybelov37/fcardre:1
    depends_on:
      - "redis"
      - "rabbit"
      - "postgres"
    links:
      - "redis"
      - "rabbit"
      - "postgres"
    ports:
      - "15010:15010"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  rabbit:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123
    ports:
      - "5432:5432"
    restart: always
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: